#Ejercicios complementarios 
# Alumno: Tiago Nahuel Guillot Duran
#1)
numero1 =(18)
#2)
numero2 = (19.5)
#3)
sumas = (numero1 + numero2)
#4)
resta = (numero1 - numero2)
multiplicacion = (numero1 * numero2)
division = (numero1 / numero2)
print (sumas)
print (resta)
print (multiplicacion)
#5)
nombre = ("tiago")
#6)
precio = (20000.1)
#7)
descuento = (0.7)
#8)
precio_final = (precio * descuento)
#9)
cadena = (str("tres tristes tigres tragan trigo en un trigal"))
#10)
longitud = len(cadena)
#11)
precio = int(2.5)
#12)
nombre = ("tiago")
apellido = ("guillot")
nombre_completo = (nombre + apellido)
print (nombre_completo)
#13)
mi_edad = (19)
mi_edad + 5
mi_edad -10
#14)
altura = (1.80)
altura * 4
altura / 3
#15)
Nombre_entero = ("TIAGONAHUELGUILLOTDURAN")
print (Nombre_entero)
print(Nombre_entero.lower())
#16)
Nombre_entero = ("TIAGONAHUELGUILLOTDURAN")
print(Nombre_entero.capitalize())